let poemForm = document.querySelector("#generate-poem")
poemForm.addEventListener("submit", displayPoem)

function displayPoem(e){
    e.preventDefault()
    let poemText = "This poem is generated by AI"
    let poemDiv = document.querySelector("#poem")
    new Typewriter('#poem', {
  strings: poemText,
  autoStart: true,
  delay:2,
  cursor: '',
});
}